### ISSUE TITLE
Metoda SzukajAsync

### ISSUE THREAD

**Issue by Kotzyk** [Kotzyk/Prawnotron#3]
Metoda _SzukajAsync_ nie umie jeszcze robić nic pożytecznego. Trzeba opracować sposób iterowania po wynikach w momencie gdy API wywali kilka obiektów i parsować do Ustawa każdy z osobna, a potem włożyć do listy.

**Comment by PiotrGretszel** [comment]
Dodałem kilka rzeczy do metody, idzie to w dobrym kierunku.

**Comment by PiotrGretszel** [comment]
Można chyba zamknąć. Metoda robi już coś pożytecznego a dokładniej to co miała robić.

**Comment by Kotzyk** [comment]
Na razie zamykam, w razie czego sam poprawię. Dobra robota, serio.
