### ISSUE TITLE
Poprawne wyszukiwanie w GUI

### ISSUE THREAD

**Issue by Kotzyk** [Kotzyk/Prawnotron#8]
Jak wyżej, żeby już sprawnie pokazywało listę ustaw z wyszukiwania i pozwalało na wpisanie artykułów, które będą przekazywane do wyciągnięcia. Wtedy uruchomi się też pobieranie treści itd.

**Comment by Kotzyk** [comment]
Pokazuje listę ustaw, jest niewątpliwy sukces

**Comment by PiotrGretszel** [comment]
Coś podziałałem, zobacz jak to teraz wygląda.
